server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://192.168.105.200:30496
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
              - X-Requested-With
              - Accept
            allowCredentials: true
      routes:
        # Ruta para ms-client
        - id: ms-client
          uri: lb://ms-client
          predicates:
            - Path=/api/v1/clients/**

        # Ruta para ms-credit
        - id: ms-credit
          uri: lb://ms-credit
          predicates:
            - Path=/api/v1/credits/**

        # Ruta para ms-creditevaluation
        - id: ms-creditevaluation
          uri: lb://ms-creditevaluation
          predicates:
            - Path=/api/v1/credit-evaluations/**

        # Ruta para ms-creditrequest
        - id: ms-creditrequest
          uri: lb://ms-creditrequest
          predicates:
            - Path=/api/v1/credit-requests/**

        # Ruta para ms-creditsimulation
        - id: ms-creditsimulation
          uri: lb://ms-creditsimulation
          predicates:
            - Path=/api/v1/credit-simulation/**

        # Ruta para ms-credittotalcost
        - id: ms-credittotalcost
          uri: lb://ms-credittotalcost
          predicates:
            - Path=/api/v1/credit-total-cost/**

        # Ruta para ms-credittracking
        - id: ms-credittracking
          uri: lb://ms-credittracking
          predicates:
            - Path=/api/v1/credit-tracking/**
