server:
  port: 8094
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditrequests-db
    username: postgres
    password: 1234
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/