server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditsimulation-db
    username: postgres
    password: 1234
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/