apiVersion: v1
kind: PersistentVolume
metadata:
  name: credit-request-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi # Memoria optimizada
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/credit-request-db-data" # Ruta para almacenar la base de datos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credit-request-db-pvc
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-request-db-deployment
  labels:
    app: credit-request-db-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: credit-request-db-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: credit-request-db-deployment
        tier: database
    spec:
      containers:
        - name: credit-request-db
          image: postgres # Imagen oficial de PostgreSQL
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 # Puerto estándar de PostgreSQL
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_GENERAL
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_GENERAL
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CREDITREQUESTS # Base de datos específica
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: credit-request-db-data
      volumes:
        - name: credit-request-db-data
          persistentVolumeClaim:
            claimName: credit-request-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: creditrequests-db-service
  labels:
    app: creditrequests-db-service
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: credit-request-db-deployment
    tier: database
  type: LoadBalancer
