apiVersion: v1
kind: PersistentVolume
metadata:
  name: credittotalcost-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 256Mi # Espacio reservado para la base de datos
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/credittotalcost-db-data" # Ruta de almacenamiento local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credittotalcost-db-pvc
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi # Espacio solicitado
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credittotalcost-db-deployment
  labels:
    app: credittotalcost-db-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: credittotalcost-db-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: credittotalcost-db-deployment
        tier: database
    spec:
      containers:
        - name: credittotalcost-db
          image: postgres # Imagen oficial de PostgreSQL
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 # Puerto estándar de PostgreSQL
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_GENERAL # Usuario general
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_GENERAL # Contraseña general
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CREDITTOTALCOSTS # Base de datos para ms-credittotalcost
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: credittotalcost-db-data
      volumes:
        - name: credittotalcost-db-data
          persistentVolumeClaim:
            claimName: credittotalcost-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: credittotalcosts-db-service
  labels:
    app: credittotalcosts-db-service
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: credittotalcost-db-deployment
    tier: database
  type: LoadBalancer
