apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-creditsimulation-deployment
  labels:
    app: ms-creditsimulation-deployment
spec:
  selector:
    matchLabels:
      app: ms-creditsimulation-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-creditsimulation-deployment
    spec:
      containers:
        - name: ms-creditsimulation
          image: z1ckk/image-ms-creditsimulation # Imagen creada para el microservicio
          ports:
            - containerPort: 8095 # Puerto del microservicio
          env:
            - name: SERVER_PORT
              value: "0" # Puerto dinámico como solicitado
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CREDITSIMULATION # Host de la base de datos
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CREDITSIMULATION # Puerto de la base de datos
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CREDITSIMULATIONS # Nombre de la base de datos
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_GENERAL # Usuario general
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_GENERAL # Contraseña general
