apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-credit-request-deployment
  labels:
    app: ms-credit-request-deployment
spec:
  selector:
    matchLabels:
      app: ms-credit-request-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-credit-request-deployment
    spec:
      containers:
        - name: ms-credit-request
          image: z1ckk/image-ms-credit-request # Imagen creada para el microservicio credit-request
          ports:
            - containerPort: 8094 # Puerto del microservicio
          env:
            - name: SERVER_PORT
              value: "0" # Puerto dinámico
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CREDITREQUESTS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CREDITREQUESTS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CREDITREQUESTS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_GENERAL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_GENERAL
