apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  # Credenciales para las bases de datos
  DB_USER_GENERAL: cG9zdGdyZXM=  # "postgres" en Base64
  DB_PASSWORD_GENERAL: cG9zdGdyZXM=