apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  # Credenciales para clients-db
  DB_USER_CLIENTS: cG9zdGdyZXM=  # "postgres" en Base64
  DB_PASSWORD_CLIENTS: MTIzNA==  # "1234" en Base64

  # Credenciales para creditevaluations-db
  DB_USER_CREDITEVALUATIONS: cG9zdGdyZXM=  # "postgres" en Base64
  DB_PASSWORD_CREDITEVALUATIONS: MTIzNA==  # "1234" en Base64

  # Credenciales para creditrequests-db
  DB_USER_CREDITREQUESTS: cG9zdGdyZXM=  # "postgres" en Base64
  DB_PASSWORD_CREDITREQUESTS: MTIzNA==  # "1234" en Base64

  # Credenciales para credits-db
  DB_USER_CREDITS: cG9zdGdyZXM=  # "postgres" en Base64
  DB_PASSWORD_CREDITS: MTIzNA==  # "1234" en Base64

  # Credenciales para creditsimulation-db
  DB_USER_CREDITSIMULATION: cG9zdGdyZXM=  # "postgres" en Base64
  DB_PASSWORD_CREDITSIMULATION: MTIzNA==  # "1234" en Base64

  # Credenciales para credittotalcosts-db
  DB_USER_CREDITTOTALCOSTS: cG9zdGdyZXM=  # "postgres" en Base64
  DB_PASSWORD_CREDITTOTALCOSTS: MTIzNA==  # "1234" en Base64

  # Credenciales para credittrackings-db
  DB_USER_CREDITTRACKINGS: cG9zdGdyZXM=  # "postgres" en Base64
  DB_PASSWORD_CREDITTRACKINGS: MTIzNA==  # "1234" en Base64
